### PR TITLE
Update image server doc

### PR DESCRIPTION
**Pull request by Xamber**
Change imageserver URL to the new one .

### CODE REVIEW

**Comment by Dusty-Meg** [comment]
Would it not be worth changing it to the new full url?
Characters would be:
https://images.evetech.net/characters/95465499/portrait?tenant=tranquility&size=128

**Review by gitAskur — DISMISSED** [review]
Short and sweet!

**Comment by CarbonAlabel** [comment]
There's other outdated info on there as well, such as the available sizes, and the proper way to get faction logos, as they're available under corporations now.

**Review by gitAskur — DISMISSED** [review]

**Review by gitAskur — APPROVED** [review]
Approve machine goes brrrrrr...

**Pull request merged**
