### PR TITLE
Remove SSO warning

### PR DESCRIPTION
**Pull request by CarbonAlabel**
While the list at https://github.com/ccpgames/sso-issues/issues hasn't been updated, the most severe issues with the v2 SSO have been fixed, so I believe the warning added in https://github.com/esi/esi-docs/pull/6 can be safely removed.

### CODE REVIEW

**Comment by GoldenGnu** [comment]
Is the issue with v2 apps not showing on https://community.eveonline.com/support/third-party-applications/ fixed? it that is the case, I think it's fair to remove the warning, otherwise, I think the warning should be changed to "only use for desktop/mobile apps".

**Comment by CarbonAlabel** [comment]
I opened this PR because I finally saw v2 apps in my third-party apps list, so I'd say it has.

**Comment by Ionaru** [comment]
Some users still cannot see apps using v2 on the third-party apps page

image

**Comment by CarbonAlabel** [comment]
@Ionaru I've seen that error show up from time to time, doubt it's related to the v2 SSO. Clearing your cookies and logging in again will most likely fix it. If it persists, or if a lot of people are getting it, might be worth taking it to https://github.com/ccpgames/sso-issues.

**Comment by tsuthers-ccpgames** [comment]
@Ionaru To assist with debugging, what are you expecting to have show up there?

**Comment by Ionaru** [comment]
That page (https://community.eveonline.com/support/third-party-applications/) is supposed to show an overview of the third-party apps that my character has logged in to, showing the scopes that app has access to and I should have the ability to revoke access.

@CarbonAlabel Even if this particular error is fixed, v2 still has many unresolved issues that, in my opinion, warrant the warning.

**Comment by tsuthers-ccpgames** [comment]
@Ionaru Specific applications you know should be there, so we can check to see if they're causing errors on the backend?

**Comment by Ionaru** [comment]
Quite a few: EVE Droid, EVE Panda, EVIE login, EVIE auth, Python SSOv2 test.

There are probably more, but those are the ones I've been using recently

**Comment by tsuthers-ccpgames** [comment]
Perfect, I've passed it on to the team that handles this :)

**Comment by tsuthers-ccpgames** [comment]
@Ionaru Can you please confirm that screenshot is from today?

**Comment by Ionaru** [comment]
The screenshot itself is from yesterday, however if I were to make a screenshot now, it would look the same.

**Comment by tsuthers-ccpgames** [comment]
@Ionaru patches that address issues looking very like this were deployed on Wednesday UTC and I don't know what timezone you're in so the timeline here is ambiguous. Please clarify for me explicitly:

You have tested this within the last 6 hours, and it is still occurring. True or false?

**Comment by Ionaru** [comment]
True

Screenshot_2019-05-24T14:13:37Z

**Comment by tsuthers-ccpgames** [comment]
Perfect, thanks!

**Comment by tsuthers-ccpgames** [comment]
Another patch addressing this has just been release, how's it looking for people now?

**Comment by Ionaru** [comment]
The community site is looking good for me :+1:

**Comment by CarbonAlabel** [comment]
I assume the third-party applications page error has now been fixed for most, if not all people. May we move ahead with this? Does @stebet have any thoughts on this?

**Comment by ddouglas** [comment]
Still affecting me

chrome_1Kko4FDXee

**Comment by CarbonAlabel** [comment]
I opened the PR to add the notice because at or around that time, alongside several minor issues, v2 refresh tokens were completely irrevocable. Since that is no longer the case, and the v2 SSO has improved much since then, I think it would be fair to remove the notice.

If there is still a significant amount of people for who the third-party applications page is inaccessible, that is a pretty bad issue that should be addressed, but unless one of the CCP devs can tell me those errors are directly caused by use of the v2 SSO, I'm going to merge this in.

**Pull request merged**
