### PR TITLE
fix broken doc link

### PR DESCRIPTION
**Pull request by KHannel**

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
What's actually broken about it? The page is available in both HTML and Markdown formats. What happens if you just remove the extension? Then maybe it'll resolve correctly depending on the context you're viewing the docs on. E.g. GH versus the actual docs website.

**Comment by KHannel** [comment]
I'm not sure where the page is available in HTML format so I can't say if it's broken there or not but the repository only has the markdown version.  The link is broken when viewing the docs through github and the file that's being linked to as "Resolve Structure IDs" (resolve_structure_ids.html) does not exist in the repository.

image

image

**Comment by KHannel** [comment]
I found the link in the published HTML docs and it works as expected there. I don't see anything in the repo that generates or converts the markdown to HTML. Can you share how I can generate the HTML or another way I can test if removing the extension works in both places?

**Review by CarbonAlabel — APPROVED** [review]

**Comment by CarbonAlabel** [comment]
Using the `.md` extension is the correct move here. That way, the link works when browsing the source, and the page generator takes care of converting it to `.html` when compiled.

Thanks for the PR!

**Pull request merged**
